server:
  port: 40210

spring:
  cloud:
    gateway:
      routes:
        - id: chat
          uri: http://localhost:8081
          predicates:
            - Path=/api/**

        - id: admin
          uri: http://localhost:5173
          predicates:
            - Path=/**