server:
  port: 40210

spring:
  cloud:
    gateway:
      routes:
        - id: chat
          uri: http://localhost:8080
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
        - id: swagger
          uri: http://localhost:8080
          predicates:
            - Path=/v3/**

        - id: admin
          uri: http://localhost:5173
          predicates:
            - Path=/**